// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgEATs199SHvsbjGJrmWnk8oGcR9yjXYQ',
    appId: '1:774207487248:web:b192301e91bb1c2080b995',
    messagingSenderId: '774207487248',
    projectId: 'lora-app-33827',
    authDomain: 'lora-app-33827.firebaseapp.com',
    storageBucket: 'lora-app-33827.appspot.com',
    measurementId: 'G-ZQBB3JG1DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Z-sRiEXeEiajTtlxeQfBaernnpcUDhw',
    appId: '1:774207487248:android:8c51e675f7582ca780b995',
    messagingSenderId: '774207487248',
    projectId: 'lora-app-33827',
    storageBucket: 'lora-app-33827.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2-GDyOGz2Cqa5zISWLo6K-d6sWlmKtpY',
    appId: '1:774207487248:ios:0583e22f283e37a280b995',
    messagingSenderId: '774207487248',
    projectId: 'lora-app-33827',
    storageBucket: 'lora-app-33827.appspot.com',
    iosBundleId: 'com.example.loraChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2-GDyOGz2Cqa5zISWLo6K-d6sWlmKtpY',
    appId: '1:774207487248:ios:8ab54e017a8f97f080b995',
    messagingSenderId: '774207487248',
    projectId: 'lora-app-33827',
    storageBucket: 'lora-app-33827.appspot.com',
    iosBundleId: 'com.example.loraChatapp.RunnerTests',
  );
}
